# Generated by Django 5.2.6 on 2025-09-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
