# Generated by Django 5.2.6 on 2025-09-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
