# Generated by Django 5.2.6 on 2025-09-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_wiki_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='wiki_link',
        ),
    ]
